namespace: dev

frontend:
  image: nginx
  replicas: 1
  servicePort: 80

userService:
  image: hashicorp/http-echo
  text: "User Service OK"
  replicas: 1

orderService:
  image: hashicorp/http-echo
  text: "Order Service OK"
  replicas: 1

apiGateway:
  image: nginx
  replicas: 1