apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /api/users {
          proxy_pass http://user-service;
        }

        location /api/orders {
          proxy_pass http://order-service;
        }
      }
    }