apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: {{ .Values.orderService.image }}
        args:
          - "-text={{ .Values.orderService.text }}"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: order
  ports:
    - port: 80
      targetPort: 5678